### PR TITLE
Fix SPM Xcode integration issue

### LINKED ISSUE #265: 🐞 [iOS] SPM doesn't compile when included in an application
**Configuration**
 - App Version: any
 - SDK Version 0.10.5
 - OS Version: any
 - Device: any
 - Xcode: 12.1, 12.2-beta.3
 
**Steps to Reproduce**
1. Open existing application OR create a new one
2. Add `https://github.com/mapbox/mapbox-events-ios` SPM dependency though the native Xcode UI
3. Add `import MapboxMobileEvents` somewhere in the project
4. Try do build the app

**Expected**
`Build succeeded` notification

**Actual**
Build errors: 
* `Could not build Objective-C module 'MapboxMobileEvents'`
* `'MapboxMobileEvents/MMEConstants.h' file not found`

**Logging**
[Sample project with SPM issue](https://github.com/mapbox/mapbox-events-ios/files/5408591/TelemetrySPMSample.zip)
image

/cc @frederoni

### PR DESCRIPTION
**Pull request by frederoni**
Fixes #265 

When integrating an SPM package with Xcode, `SWIFT_PACKAGE` is undefined. This causes the umbrella header to behave
incorrectly. By folding MME sources into `Sources/MapboxMobileEvents/include` (following the SPM [C language targets documentation](https://github.com/apple/swift-package-manager/blob/main/Documentation/Usage.md#creating-c-language-targets)) we can use the same umbrella for CocoaPods, SPM, and Carthage because now SPM inside Xcode will also find angle bracket includes such as `<MapboxMobileEvents/MMEConstants.h>`.

@alfwatt, IIRC, you had some guidelines about groups vs folder structure, would you mind verifying that here?

cc @OdNairy  @mr1sunshine @nagineni

### CODE REVIEW

**Comment by OdNairy** [comment]
I can confirm that this branch fixes the original issue for me. 
However, I still have a runtime issue `dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
` which is related to the Xcode bugs (Xcode 12.2 Beta 3).

**Comment by OdNairy** [comment]
Do we have an ETA for this PR?

**Comment by frederoni** [comment]
>  I still have a runtime issue dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents

Can you confirm that this was fixed by removing the enforced dynamic linking?

**Comment by OdNairy** [comment]
> > I still have a runtime issue dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
> 
> Can you confirm that this was fixed by removing the enforced dynamic linking?

Yes, I can confirm it. 
Xcode 12.2-beta.3 works correctly.

**Review by alfwatt — APPROVED** [review]
Was able to build this with my [aw-development](https://github.com/mapbox/mobile-telemetry-example-ios/tree/aw-development) branch, test script runs cleanly at the command line

**Pull request merged**
