### PR TITLE
Static framework should define module

### LINKED ISSUE #73: Declare that the framework defines a module
With the new build system that’s on by default in Xcode 10, static frameworks are expected to set the `DEFINES_MODULE` build setting. As seen in mapbox/mapbox-navigation-ios#1748, CocoaPods now errors out if a static framework dependency doesn’t declare the setting. mapbox/mapbox-gl-native#12971 made this change in the map SDK. It should be safe for the standard way in which the navigation SDK depends on this library, but I’m not sure how it interacts with the magical way in which this library is integrated into the map SDK.

/cc @rclee @friedbunny

### PR DESCRIPTION
**Pull request by frederoni**
Fixes #73 

The dynamic framework already defines a module, the static doesn't.

cc @rclee @1ec5

### CODE REVIEW

**Comment by rclee** [comment]
Thanks @frederoni, shouldn't `s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }` be added to the `podspec` as well?

**Comment by frederoni** [comment]
@rclee correct. As it stands now, it would only be fixed when integrating with Carthage.

**Comment by paul019** [comment]
So this pull request doesn't fix the issue when importing the library with Cocoapods?

**Comment by frederoni** [comment]
@paul019 I amended a change and force pushed a commit (`79d29f1df5a9187481f5c9ac8fa13430d1f04139`) after I wrote https://github.com/mapbox/mapbox-events-ios/pull/85#issuecomment-432382239.

Please try `79d29f1df5a9187481f5c9ac8fa13430d1f04139`.

**Comment by paul019** [comment]
I am very sorry, but I can try this out only tomorrow.

In the end I don't want to install the pod `MapboxMobileEvents`, but `MapboxNavigation`. Is it's install problem supposed to be fixed by this Pull request, too?

**Comment by frederoni** [comment]
@paul019 yes, this PR should address the issue you described in https://github.com/mapbox/mapbox-navigation-ios/issues/1791

MapboxNavigation depends on MapboxMobileEvents. By specifying a transient dependency, we'll make sure that this fix works for you, then we can make a new release and you can remove the transient dependency.

**Comment by paul019** [comment]
@frederoni I tried out your code and all pods were installed successfully! Thank you very much!

But how can I use the working version of `MapboxNavigation` now? I am relatively new to Cocoapods and don't know what a "transient dependency" is...

**Comment by frederoni** [comment]
@paul019 Just keep this line:
```ruby
pod 'MapboxMobileEvents', :git => 'https://github.com/mapbox/mapbox-events-ios.git', :commit => "79d29f1df5a9187481f5c9ac8fa13430d1f04139"
```

in your Podfile. This is called a transient dependency because you are not following the dependency tree and resolving the MapboxMobileEvents version that MapboxNavigation tries to pull in.

You can delete that line when we release a new version of MapboxMobileEvents and MapboxNavigation.

**Comment by paul019** [comment]
Now I've a Podfile like this:

```
target 'pq-app-v2' do
  pod 'Mapbox-iOS-SDK', '~> 4.5'
  pod 'MapboxMobileEvents',
    :git => 'https://github.com/mapbox/mapbox-events-ios.git',
    :commit => "79d29f1df5a9187481f5c9ac8fa13430d1f04139"
  pod 'MapboxNavigation', '~> 0.22.0'
  ...
```

I can successfully run `pod repo update && pod install`, but when compiling the project in Xcode, I get seven errors that were not there before: To give an example, in some library file the error `Type 'Number' does not conform to protocol 'Equatable'` occurs.

**Comment by frederoni** [comment]
@paul019 what version of Xcode and Swift are you using? It looks like you're pre-4.0. The last release of MapboxNavigation compatible with Swift 3.2 was v0.10.1.

**Comment by 1ec5** [comment]
(It’s called a “transitive dependency”, by the way.)

**Comment by paul019** [comment]
I've now updated Swift to version 4.0 and get the errors anyway...

Do you have any idea, how to solve this? Do I have to update to an even newer version?

**Comment by rclee** [comment]
@paul019 You could try a higher Swift version. According to [this issue](https://github.com/mapbox/mapbox-navigation-ios/issues/1538#issuecomment-402675009) Xcode 9.4 (Swift `4.1`) should work for this error.

**Review by rclee — APPROVED** [review]

**Comment by paul019** [comment]
Hi! I've two remaining issues:

1. Although you've merged this into master I can't remove this line of code in the Podfile without getting the above mentioned CocoaPod errors: `pod 'MapboxMobileEvents', :git => 'https://github.com/mapbox/mapbox-events-ios.git', :commit => "79d29f1df5a9187481f5c9ac8fa13430d1f04139"`.

2. When I run a `pod install` (with the errorless setup in the Podfile) and then compile the project in Xcode (Swift 4.2) I get this error: `'MapboxDirections/MapboxDirections.h' file not found`.
bildschirmfoto 2018-11-05 um 20 40 35

How can I solve those two problems? Thank you very much for your great work and help!

**Comment by paul019** [comment]
I've realized, that I forgot to run `pod repo update`. After doing that and running `pod install`, CocoaPod gets stuck at the installation process after printing this line: `Installing MapboxNavigationNative 3.3.1 (was 3.2.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)`. I found similar issues on Github, but no workaround worked for me so far.

Do you know, how I can solve this problem?

(My Xcode version: `Version 10.1 (10B61)`)

**Comment by paul019** [comment]
@frederoni @rclee @1ec5 After trying various workarounds and spending hours of bug fixing, I've still the two above mentioned issues. Especially issue 2 is very annoying and prohibits me to work at my project. It would help me a lot, when you could give me an advice.

Note:
I've tried Xcode 10 (Swift 4.2) as well as Xcode 9 (Swift 4.1). Both versions resulted in the second issue described in my last post.

**Comment by paul019** [comment]
I've now found a solution for my issue: By commenting out the line of code, that produces the error (see Xcode screenshot), I can solve the issues without creating new errors. I now that this sounds stupid, but is this line of code necessary? It appears to me, that its not important and that its import is not needed in the file.

**Comment by paul019** [comment]
@frederoni @rclee @1ec5 Can this hacky fix work for me or does it change any functionality of the library? If yes, can you please provide another fix/workaround for my issue? I can't find anything regarding it on the internet...

**Comment by paul019** [comment]
@frederoni @rclee @1ec5 An answer would be very appreciated. Or should I open a new issue for this?

**Comment by frederoni** [comment]
@paul019 please open a new ticket in [MapboxDirections.swift](https://github.com/mapbox/MapboxDirections.swift) or [mapbox-navigation-ios](https://github.com/mapbox/mapbox-navigation-ios).

**Comment by paul019** [comment]
@frederoni I've now opened a new ticket in mapbox-navigation-ios:
https://github.com/mapbox/mapbox-navigation-ios/issues/1816

**Pull request merged**
